apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: student-app-api
spec:
  hosts:
  - student-app-api
  http:
  - route:
    - destination:
        host: student-app-api
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: student-app-client
spec:
  hosts:
  - student-app-client
  http:
  - route:
    - destination:
        host: student-app-client
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mongo
spec:
  hosts:
  - mongo
  http:
  - route:
    - destination:
        host: mongo
        subset: v1